POST http://localhost:3000/signup HTTP/1.1
content-type: application/json

{
    "email": "gustavopetruzzi19@gmail.com",
    "username": "yustix",
    "password": "1161544761"
}

###

GET http://localhost:3000/env HTTP/1.1